import { DataUtil } from "@syncfusion/ej2-data";
export let employeeData: Object[] = [{
  'EmployeeID': 1,
  'Name': 'Davolio',
  'Grade': 'L.K.G',
  'Title': 'Sales Representative',
  'TitleOfCourtesy': 'Ms.',
  'BirthDate': new Date(-664743600000),
  'HireDate': new Date(704692800000),
  'Address': '507 - 20th Ave. E.\r\nApt. 2A',
  'City': 'Seattle',
  'PaidAmount': '20000',
  'TotalAmount': '30000',
  'Attendance': '100%',
  'HomePhone': '(206) 555-9857',
  'TotalDay': '280',
  'Photo': { 'Length': 21626 },
  'Notes': 'Education includes a BA in psychology from Colorado State University in 1970.  She also completed\
  \'The Art of the Cold Call.\'  Nancy is a member of Toastmasters International.',
  'ReportsTo': 2,
  'PhotoPath': 'http://accweb/emmployees/davolio.bmp'
}, {
  'EmployeeID': 2,
  'Name': 'Fuller',
  'Grade': 'L.K.G',
  'Title': 'Vice President, Sales',
  'TitleOfCourtesy': 'Dr.',
  'BirthDate': new Date(-563828400000),
  'HireDate': new Date(713764800000),
  'Address': '908 W. Capital Way',
  'City': 'Tacoma',
  'PaidAmount': 'WA',
  'TotalAmount': '98401',
  'Attendance': 'USA',
  'HomePhone': '(206) 555-9482',
  'TotalDay': '3457',
  'Photo': { 'Length': 21626 },
  'Notes': 'Andrew received his BTS commercial in 1974 and a Ph.D. in international marketing from the University of \
  Dallas in 1981.  He is fluent in French and Italian and reads German.  He joined the company as a sales representative, \
  was promoted to sales manager in January 1992 and to vice president of sales in March 1993.  Andrew is a member of the \
  Sales Management Roundtable, the Seattle Chamber of Commerce, and the Pacific Rim Importers Association.',
  'ReportsTo': 7,
  'PhotoPath': 'http://accweb/emmployees/fuller.bmp'
}, {
  'EmployeeID': 3,
  'Name': 'Leverling',
  'Grade': 'U.K.G',
  'Title': 'Sales Representative',
  'TitleOfCourtesy': 'Ms.',
  'BirthDate': new Date(-200088000000),
  'HireDate': new Date(702104400000),
  'Address': '722 Moss Bay Blvd.',
  'City': 'Kirkland',
  'PaidAmount': 'WA',
  'TotalAmount': '98033',
  'Attendance': 'USA',
  'HomePhone': '(206) 555-3412',
  'TotalDay': '3355',
  'Photo': { 'Length': 21722 },
  'Notes': 'Janet has a BS degree in chemistry from Boston College (1984). \
   She has also completed a certificate program in food retailing management.\
   Janet was hired as a sales associate in 1991 and promoted to sales representative in February 1992.',
  'ReportsTo': 2,
  'PhotoPath': 'http://accweb/emmployees/leverling.bmp'
}, {
  'EmployeeID': 4,
  'Name': 'Peacock',
  'Grade': 'Margaret',
  'Title': 'Sales Representative',
  'TitleOfCourtesy': 'Mrs.',
  'BirthDate': new Date(-1018814400000),
  'HireDate': new Date(736401600000),
  'Address': '4110 Old Redmond Rd.',
  'City': 'Redmond',
  'PaidAmount': 'WA',
  'TotalAmount': '98052',
  'Attendance': 'USA',
  'HomePhone': '(206) 555-8122',
  'TotalDay': '5176',
  'Photo': { 'Length': 21626 },
  'Notes': 'Margaret holds a BA in English literature from Concordia College (1958) and an MA from the American \
  Institute of Culinary Arts (1966).  She was assigned to the London office temporarily from July through November 1992.',
  'ReportsTo': 2,
  'PhotoPath': 'http://accweb/emmployees/peacock.bmp'
}, {
  'EmployeeID': 5,
  'Name': 'Buchanan',
  'Grade': 'Steven',
  'Title': 'Sales Manager',
  'TitleOfCourtesy': 'Mr.',
  'BirthDate': new Date(-468010800000),
  'HireDate': new Date(750830400000),
  'Address': '14 Garrett Hill',
  'City': 'London',
  'PaidAmount': null,
  'TotalAmount':
  'SW1 8JR',
  'Attendance': 'UK',
  'HomePhone': '(71) 555-4848',
  'TotalDay': '3453',
  'Photo': { 'Length': 21626 },
  'Notes': 'Steven Buchanan graduated from St. Andrews University, Scotland, with a BSC degree in 1976.  Upon joining the company as \
  a sales representative in 1992, he spent 6 months in an orientation program at the Seattle office and then returned to his permanent \
  post in London.  He was promoted to sales manager in March 1993.  Mr. Buchanan has completed the courses \'Successful \
  Telemarketing\' and \'International Sales Management.\'  He is fluent in French.',
  'ReportsTo': 2,
  'PhotoPath': 'http://accweb/emmployees/buchanan.bmp'
}, {
  'EmployeeID': 6,
  'Name': 'Suyama',
  'Grade': 'Michael',
  'Title': 'Sales Representative',
  'TitleOfCourtesy': 'Mr.',
  'BirthDate': new Date(-205185600000),
  'HireDate': new Date(750830400000),
  'Address': 'Coventry House\r\nMiner Rd.',
  'City': 'London',
  'PaidAmount': null,
  'TotalAmount': 'EC2 7JR',
  'Attendance': 'UK',
  'HomePhone': '(71) 555-7773',
  'TotalDay': '428',
  'Photo': { 'Length': 21626 },
  'Notes': 'Michael is a graduate of Sussex University (MA, economics, 1983) and the University of California at Los Angeles \
  (MBA, marketing, 1986).  He has also taken the courses \'Multi-Cultural Selling\' and \'Time Management for the Sales Professional.\'  \
  He is fluent in Japanese and can read and write French, Portuguese, and Spanish.',
  'ReportsTo': 5,
  'PhotoPath': 'http://accweb/emmployees/davolio.bmp'
}, {
  'EmployeeID': 7,
  'Name': 'King',
  'Grade': 'Robert',
  'Title': 'Sales Representative',
  'TitleOfCourtesy': 'Mr.',
  'BirthDate': new Date(-302731200000),
  'HireDate': new Date(757486800000),
  'Address': 'Edgeham Hollow\r\nWinchester Way',
  'City': 'London',
  'PaidAmount': null,
  'TotalAmount': 'RG1 9SP',
  'Attendance': 'UK',
  'HomePhone': '(71) 555-5598',
  'TotalDay': '465',
  'Photo': { 'Length': 21626 },
  'Notes': 'Robert King served in the Peace Corps and traveled extensively before completing his degree in English at the \
  University of Michigan in 1992, the year he joined the company.  After completing a course entitled \'Selling in Europe,\' \
  he was transferred to the London office in March 1993.',
  'ReportsTo': 5,
  'PhotoPath': 'http://accweb/emmployees/davolio.bmp'
}, {
  'EmployeeID': 8,
  'Name': 'Callahan',
  'Grade': 'Laura',
  'Title': 'Inside Sales Coordinator',
  'TitleOfCourtesy': 'Ms.',
  'BirthDate': new Date(-377982000000),
  'HireDate': new Date(762843600000),
  'Address': '4726 - 11th Ave. N.E.',
  'City': 'Seattle',
  'PaidAmount': 'WA',
  'TotalAmount': '98105',
  'Attendance': 'USA',
  'HomePhone': '(206) 555-1189',
  'TotalDay': '2344',
  'Photo': { 'Length': 21626 },
  'Notes': 'Laura received a BA in psychology from the University of Washington.  She has also completed a course in business \
  French.  She reads and writes French.',
  'ReportsTo': 2,
  'PhotoPath': 'http://accweb/emmployees/davolio.bmp'
}, {
  'EmployeeID': 9,
  'Name': 'Dodsworth',
  'Grade': 'Anne',
  'Title': 'Sales Representative',
  'TitleOfCourtesy': 'Ms.',
  'BirthDate': new Date(-123966000000),
  'HireDate': new Date(784875600000),
  'Address': '7 Houndstooth Rd.',
  'City': 'London',
  'PaidAmount': null,
  'TotalAmount': 'WG2 7LT',
  'Attendance': 'UK',
  'HomePhone': '(71) 555-4444',
  'TotalDay': '452',
  'Photo': { 'Length': 21626 },
  'Notes': 'Anne has a BA degree in English from St. Lawrence College.  She is fluent in French and German.',
  'ReportsTo': 5,
  'PhotoPath': 'http://accweb/emmployees/davolio.bmp'
}];
